add translations
vtex/omnishipping pull request #1358
Opened 2020-09-29 15:06 UTC by dvm1984

#### What is the purpose of this pull request?
added missing translations.

2020-09-29 15:12 UTC, dvm1984 commented on messages/de.json
> +  "omnishipping.locatePickupPoint": "Suchen Sie einen Ort zur Ladenabholung",
wait for confirmation on wording

2020-10-08 21:21 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.locatePickupPoint": "Suchen Sie einen Ort zur Ladenabholung",
@dvm1984 any news about it?

2020-10-08 21:25 UTC, darlenedms commented on messages/bg.json
> +  "omnishipping.selectPickupPoint": "Изберете място за получаване в магазин ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Изберете място за получаване в магазин",
```

2020-10-08 21:25 UTC, darlenedms commented on messages/ca.json
> +  "omnishipping.selectPickupPoint": "Selecciona un lloc de recollida en botiga ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Selecciona un lloc de recollida en botiga",
```

2020-10-08 21:26 UTC, darlenedms commented on messages/da.json
> +  "omnishipping.selectPickupPoint": "Vælg et afhentningssted ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Vælg et afhentningssted",
```

2020-10-08 21:26 UTC, darlenedms commented on messages/el.json
> +  "omnishipping.selectPickupPoint": "Επιλέξτε τοποθεσία με Παραλαβή στο Κατάστημα ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Επιλέξτε τοποθεσία με Παραλαβή στο Κατάστημα",
```

2020-10-08 21:26 UTC, darlenedms commented on messages/fi.json
> +  "omnishipping.selectPickupPoint": "Valitse myymälänoutopiste ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Valitse myymälänoutopiste",
```

2020-10-08 21:27 UTC, darlenedms commented on messages/it.json
> +  "omnishipping.selectPickupPoint": "Seleziona un punto di ritiro ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Seleziona un punto di ritiro",
```

2020-10-08 21:27 UTC, darlenedms commented on messages/ro.json
> +  "omnishipping.selectPickupPoint": "Alege un punct de ridicare din magazin ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Alege un punct de ridicare din magazin",
```

2020-10-08 21:27 UTC, darlenedms commented on messages/ru.json
> +  "omnishipping.selectPickupPoint": "Выберите пункт выдачи в магазине ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Выберите пункт выдачи в магазине",
```

2020-10-08 21:28 UTC, darlenedms commented on messages/sk.json
> +  "omnishipping.selectPickupPoint": "Vybrať odberné miesto na Vyzdvihnutie v obchode ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Vybrať odberné miesto na Vyzdvihnutie v obchode",
```

2020-10-08 21:28 UTC, darlenedms commented on messages/sl.json
> +  "omnishipping.selectPickupPoint": "Izberite stran Prevzemi v trgovini ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Izberite stran Prevzemi v trgovini",
```

2020-10-08 21:28 UTC, darlenedms commented on messages/sv.json
> +  "omnishipping.selectPickupPoint": "Välj en hämtning i butik ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Välj en hämtning i butik",
```

2020-10-08 21:29 UTC, darlenedms commented on messages/uk.json
> +  "omnishipping.selectPickupPoint": "Виберіть пункт видачі в магазині ",
Remove extra space.
```suggestion
  "omnishipping.selectPickupPoint": "Виберіть пункт видачі в магазині",
```

2020-10-08 21:32 UTC, darlenedms commented on messages/da.json
> +  "omnishipping.deliveryAddressTitle": "Udfyld dine adresseoplysninger ",
Remove extra space.
```suggestion
  "omnishipping.deliveryAddressTitle": "Udfyld dine adresseoplysninger",
```

2020-10-08 21:39 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.shippingEstimatePickup-bd": "{timeAmount, plural, =0 {Heute fertig} one {Fertig in# Werktagen} other {Fertig in# Werktagen}}",
Add missing spaces.
```suggestion
  "omnishipping.shippingEstimatePickup-bd": "{timeAmount, plural, =0 {Heute fertig} one {Fertig in # Werktagen} other {Fertig in # Werktagen}}",
```

2020-10-08 21:39 UTC, jeffersontuc commented on messages/el.json
> +  "omnishipping.shippingEstimate-m": "{timeAmount, plural, =0 {αμέσως τώρα} one {σε# λεπτό} other {έως# λεπτά}}",
missing blank space before the `#`

2020-10-08 21:39 UTC, jeffersontuc commented on messages/el.json
> +  "omnishipping.scheduledDeliveryPartial": "{amount, plural, =0 { } one {Προγραμματισμός# προϊόντος} other {Προγραμματισμός # προϊόντων}}",
ditto

2020-10-08 21:39 UTC, jeffersontuc commented on messages/da.json
> +  "omnishipping.shippingEstimate-d": "{timeAmount, plural, =0 {i dag} one {om  # dage} other {maksimum # dage}}",
there's 2 blank spaces after `om`

2020-10-08 21:39 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.shippingEstimate-bd": "{timeAmount, plural, =0 {heute} one {auf# Unternehmen Tag} other {maximal von # Unternehmen Tage}}",
Add missing space.
```suggestion
  "omnishipping.shippingEstimate-bd": "{timeAmount, plural, =0 {heute} one {auf # Unternehmen Tag} other {maximal von # Unternehmen Tage}}",
```

2020-10-08 21:40 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.shippingEstimate-d": "{timeAmount, plural, =0 {heute} one {auf# Tag} other {maximal von # Tage}}",
Add missing space.
```suggestion
  "omnishipping.shippingEstimate-d": "{timeAmount, plural, =0 {heute} one {auf # Tag} other {maximal von # Tage}}",
```

2020-10-08 21:40 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.shippingEstimate-h": "{timeAmount, plural, =0 {jetzt} one {in# Stunden} other {bis zu # Stunden}}",
Add missing space.
```suggestion
  "omnishipping.shippingEstimate-h": "{timeAmount, plural, =0 {jetzt} one {in # Stunden} other {bis zu # Stunden}}",
```

2020-10-08 21:40 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.shippingEstimate-m": "{timeAmount, plural, =0 {Im Augenblick} one {auf# minute} other {bis zu # Minuten}}",
Add missing space.
```suggestion
  "omnishipping.shippingEstimate-m": "{timeAmount, plural, =0 {Im Augenblick} one {auf # minute} other {bis zu # Minuten}}",
```

2020-10-08 21:41 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.shippingEstimatePickup-h": "{timeAmount, plural, =0 {Abholbereit} one {Abholbereit in# Stunden} other {Abholbereit in # Stunden}}",
Add missing space.
```suggestion
  "omnishipping.shippingEstimatePickup-h": "{timeAmount, plural, =0 {Abholbereit} one {Abholbereit in # Stunden} other {Abholbereit in # Stunden}}",
```

2020-10-08 21:41 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.shippingEstimatePickup-m": "{timeAmount, plural, =0 {Abholbereit} one {Fertig in# Minuten} other {Fertig in# Minuten }}",
Add missing spaces.
```suggestion
  "omnishipping.shippingEstimatePickup-m": "{timeAmount, plural, =0 {Abholbereit} one {Fertig in # Minuten} other {Fertig in # Minuten }}",
```

2020-10-08 21:42 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.scheduledDeliveryPartial": "{amount, plural, =0 { } one {Abbhol-Wunschtermin# Artikel} other {Abbhol-Wunschtermin# Artikel}}",
Add missing spaces.
```suggestion
  "omnishipping.scheduledDeliveryPartial": "{amount, plural, =0 { } one {Abbhol-Wunschtermin # Artikel} other {Abbhol-Wunschtermin # Artikel}}",
```

2020-10-08 21:42 UTC, darlenedms commented on messages/de.json
> +  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {#Artikel nicht verfügbar} other {#Artikel nicht verfügbar}}",
Add missing space.
```suggestion
  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# Artikel nicht verfügbar} other {#Artikel nicht verfügbar}}",
```

2020-10-08 21:47 UTC, darlenedms commented on messages/fr.json
> +  "omnishipping.removeConfirmationModal.body": "{items, plural, =0 {} one {Supprimer l'article du chariot ?} other {Supprimer # articles du chariot ?}}",
Remove extra space.
```suggestion
  "omnishipping.removeConfirmationModal.body": "{items, plural, =0 {} one {Supprimer l'article du chariot?} other {Supprimer # articles du chariot?}}",
```

2020-10-08 21:48 UTC, darlenedms commented on messages/fr.json
> +  "omnishipping.unavailableDeliveryAvailablePickup": "{items, plural, =0 {} one {L'article suivant ne peut pas être expédié. Il est possible de le récupérer à partir de un point de collecte.} other {
Remove extra space.
```suggestion
  "omnishipping.unavailableDeliveryAvailablePickup": "{items, plural, =0 {} one {L'article suivant ne peut pas être expédié. Il est possible de le récupérer à partir de un point de collecte.} other {{items} les articles ne peuvent pas être expédiés .{br}Il est possible de les récupérer à partir de un point de collecte ou bien supprimez-les de votre chariot.}}",
```

2020-10-08 21:51 UTC, darlenedms commented on messages/fr.json
> +  "omnishipping.errorId": "ErrorId : {errorId}",
Remove extra space.
```suggestion
  "omnishipping.errorId": "ErrorId: {errorId}",
```

2020-10-08 21:55 UTC, darlenedms commented on messages/ro.json
> +  "omnishipping.removeButtonLabel": "Șterge ",
Remove extra space.
```suggestion
  "omnishipping.removeButtonLabel": "Șterge",
```

2020-10-08 21:57 UTC, darlenedms commented on messages/ro.json
> +  "omnishipping.askGeolocationInstructions": "Selectează „Permite\" în pop-up-ul browserului",
Change quotation mark.
```suggestion
  "omnishipping.askGeolocationInstructions": "Selectează „Permite“ în pop-up-ul browserului",
```

2020-10-08 22:03 UTC, darlenedms commented on messages/bg.json
> +  "omnishipping.deliveryWindowsSummarytime": "между {startDate} и {endDate}",
This is a good key to refactor in the entire project if you want.
```suggestion
  "omnishipping.deliveryWindowsSummaryTime": "между {startDate} и {endDate}",
```

2020-10-08 22:09 UTC, darlenedms requested changes
😬

2020-10-09 13:57 UTC, darlenedms approved these changes

2020-10-09 14:10 UTC, wdsrocha commented
`aditionalInfo` should be `additionalInfo` (double d). Can I make a commit changing all the occurrences?

2020-10-09 14:12 UTC, jeffersontuc commented
> `aditionalInfo` should be `additionalInfo` (double d). Can I make a commit changing all the occurrences?

sure!

2020-10-09 14:14 UTC, wdsrocha commented on messages/sk.json
> +  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# položka nedostupná} other {# položky nedostupné (# položiek nedostupných}}",
I think this should be
```suggestion
  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# položka nedostupná} other {# položky nedostupné {# položiek nedostupných}}",
```

2020-10-09 14:37 UTC, lucasecdb commented on messages/sk.json
> +  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# položka nedostupná} other {# položky nedostupné (# položiek nedostupných}}",
changing this would cause a syntax error I think, because there would be a missing `}` in the end.. this message seems to be weird

2020-10-09 14:46 UTC, wdsrocha commented on messages/fr.json
> +  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {#article non disponible} other {# article non disponible}}",
```suggestion
  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# article non disponible} other {# article non disponible}}",
```

2020-10-09 15:26 UTC, jeffersontuc commented on messages/sk.json
> +  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# položka nedostupná} other {# položky nedostupné (# položiek nedostupných}}",
@dvm1984 What should be the message in this case?

2020-10-09 15:56 UTC, wdsrocha commented on messages/sk.json
> +  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# položka nedostupná} other {# položky nedostupné (# položiek nedostupných}}",
Looking at similar messages + syntax + translation, I now think it should be `)` on the other side
```suggestion
  "omnishipping.unavailableItemsAmount": "{itemsAmount, plural, =0 {} one {# položka nedostupná} other {# položky nedostupné (# položiek nedostupných)}",
```

2020-10-09 18:15 UTC, darlenedms approved these changes

2020-10-09 18:17 UTC, wdsrocha approved these changes

2020-10-09 18:46 UTC, merged

2020-10-15 19:27 UTC, dvm1984 commented on messages/de.json
> +  "omnishipping.locatePickupPoint": "Suchen Sie einen Ort zur Ladenabholung",
confirmed