update crowdin.yml, CHANGELOG.md, fr.json, it.json, nl.json and ro.js…
vtex/omnishipping pull request #1361
Opened 2020-11-17 19:05 UTC by camilavcoutinho

#### What is the purpose of this pull request?
update french, dutch, romanian and italian translations

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-12-09 18:51 UTC, lucasecdb requested changes
there are a lot of changes in the messages keys, and I checked the `messages/en.json` file and they're correct there.. is there something out of sync in the crowdin integration that is exposing the old messages keys?

2020-12-09 18:51 UTC, lucasecdb commented on messages/fr.json
> +  "omnishipping.awatingData": "En attente de plus d'informations",
why this change?

2020-12-09 18:51 UTC, lucasecdb commented on messages/fr.json
> +  "omnishipping.deliveryWindowsSummarytime": "entre {startDate} et {endDate}",
ditto

2020-12-09 18:51 UTC, lucasecdb commented on messages/fr.json
> +  "omnishipping.aditionalInfo": "Autres informations",
ditto

2020-12-09 18:51 UTC, lucasecdb commented on messages/it.json
> +  "omnishipping.awatingData": "In attesa di maggiori informazioni",
ditto

2020-12-10 14:02 UTC, dvm1984 commented on messages/fr.json
> +  "omnishipping.awatingData": "En attente de plus d'informations",
this is very strange. Maybe source strings in en.json has the typo?

2020-12-10 14:27 UTC, lucasecdb commented on messages/fr.json
> +  "omnishipping.awatingData": "En attente de plus d'informations",
they don't have the typo, I checked

2020-12-10 14:32 UTC, dvm1984 commented on messages/fr.json
> +  "omnishipping.awatingData": "En attente de plus d'informations",
must revert changes to keys then.

2020-12-17 17:16 UTC, dvm1984 approved these changes

2020-12-17 17:46 UTC, lucasecdb approved these changes

2020-12-17 19:32 UTC, merged