CHK-482: Fix check for number field validity
vtex/omnishipping pull request #1367
Opened 2021-01-07 13:57 UTC by lucasecdb

#### What is the purpose of this pull request?

Update the checks for the number validity to use `address.number.valid`.

#### What problem is this solving?

Fix the checks for the number validity, that where previously using the `address.number.value` instead of `address.number.valid`, which caused issues on countries that do not have number in the addresses.

#### How should this be manually tested?

[Workspace](https://lucas--vtexgame1geo.myvtex.com/checkout/cart/add?sku=312&qty=1&seller=1&sc=2).

You can check this works by using the "United Emirate Arabes" country in the workspace above and with the address "W Corniche Road" (you can select the ~first~ only option). You should be able to proceed to the payment step without issue.

#### Screenshots or example usage

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-01-07 14:08 UTC, wdsrocha requested changes
LGTM, but the changelog is missing

2021-01-07 14:09 UTC, lucasecdb commented
> LGTM, but the changelog is missing

done :-)

2021-01-07 14:14 UTC, wdsrocha submitted a review, later dismissed

2021-01-07 20:15 UTC, darlenedms commented on react/containers/DeliveryChannelsContainer.js
> +      // For unnmapped countries, we don't want to update
```suggestion
      // For unmapped countries, we don't want to update
```
😝

2021-01-07 22:54 UTC, caetano1 commented
Hey, @lucasecdb ! I've tested and tried to finish the purchase using "boleto bancário", but after clicking on "buy", VTEX ID kept popping up to me, and repopping after authentication using key sent to email. Is it related to this PR?

2021-01-08 12:38 UTC, lucasecdb commented
> Hey, @lucasecdb ! I've tested and tried to finish the purchase using "boleto bancário", but after clicking on "buy", VTEX ID kept popping up to me, and repopping after authentication using key sent to email. Is it related to this PR?

I don't think so. VTEX ID is sometimes shown when you're using a second purchase account during the place order, according to [this article](https://help.vtex.com/faq/por-que-foi-solicitado-login-no-checkout-finalizacao-de-compra--frequentlyAskedQuestions_2705).

2021-01-08 13:35 UTC, alvim approved these changes

2021-01-08 18:14 UTC, wdsrocha approved these changes

2021-01-08 20:53 UTC, caetano1 commented
> > Hey, @lucasecdb ! I've tested and tried to finish the purchase using "boleto bancário", but after clicking on "buy", VTEX ID kept popping up to me, and repopping after authentication using key sent to email. Is it related to this PR?
> 
> I don't think so. VTEX ID is sometimes shown when you're using a second purchase account during the place order, according to [this article](https://help.vtex.com/faq/por-que-foi-solicitado-login-no-checkout-finalizacao-de-compra--frequentlyAskedQuestions_2705).

Hmm got it! Thank you!

2021-01-14 17:38 UTC, jeffersontuc approved these changes

2021-01-14 17:39 UTC, jeffersontuc commented
I just saw it needs rebase

2021-01-14 19:18 UTC, darlenedms approved these changes

2021-01-14 19:19 UTC, wdsrocha approved these changes

2021-01-18 18:12 UTC, merged